# Generated by Django 5.2.7 on 2025-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                (
                    'client_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Nome'),
                ),
                (
                    'nickname',
                    models.CharField(
                        blank=True, max_length=100, verbose_name='Apelido'
                    ),
                ),
                (
                    'phone_number',
                    models.CharField(max_length=20, verbose_name='Telefone'),
                ),
                (
                    'client_debts',
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name='Dívidas do Cliente',
                    ),
                ),
                (
                    'photo',
                    models.ImageField(
                        upload_to='client_photos/',
                        verbose_name='Foto do Cliente',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Data de Criação'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Data de Atualização'
                    ),
                ),
            ],
        ),
    ]
