# Generated by Django 5.2.7 on 2025-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='Avulso', max_length=255, verbose_name='Nome'),
        ),
    ]
