# Generated by Django 5.2.7 on 2025-11-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='client_photos/',
                verbose_name='Foto do Cliente',
            ),
        ),
    ]
