# Generated by Django 5.2.7

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_initial_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Quitado')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Quitação')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='clients.client', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Quitação de Dívida',
                'verbose_name_plural': 'Quitações de Dívidas',
                'ordering': ['-created_at'],
            },
        ),
    ]

