# Generated by Django 5.2.7 on 2025-11-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product')},
        ),
    ]
