# Generated by Django 5.2.7 on 2025-11-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0002_alter_saleitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='products.product',
            ),
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='unit_price',
        ),
    ]
