# Generated by Django 5.2.7 on 2025-11-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_saleitem_price_alter_saleitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client_name',
            field=models.CharField(blank=True, default='Avulso', max_length=255),
        ),
    ]
