# Generated by Django 5.2.7 on 2025-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'product_id',
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Nome'),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('SC', 'Sem Categoria'),
                            ('CE', 'Cerveja'),
                            ('RE', 'Refrigerante'),
                            ('EN', 'Energético'),
                            ('PE', 'Petiscos'),
                            ('AL', 'Alimentos'),
                            ('WH', 'Whisky'),
                            ('VO', 'Vodka'),
                            ('SU', 'Sucos'),
                            ('OU', 'Outros'),
                        ],
                        default='SC',
                        max_length=20,
                        verbose_name='Categoria',
                    ),
                ),
                (
                    'sale_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name='Preço de Venda',
                    ),
                ),
                (
                    'cost_price',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name='Preço de Custo',
                    ),
                ),
                (
                    'quantity',
                    models.IntegerField(default=0, verbose_name='Quantidade'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Data de Criação'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Data de Atualização'
                    ),
                ),
            ],
        ),
    ]
