# Generated by Django 5.2.7 on 2025-11-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_quantity',
            field=models.IntegerField(default=0, verbose_name='Estoque Baixo'),
        ),
    ]
